// Design philosophy: present live account data with the same restrained Ernest hierarchy — compact, legible, and explicit about loading or permission states.

export type DerivAccount = { id: string; label: string; accountType: string; currency: string; balance: number | null; isDemo: boolean };
function numericValue(value: unknown) { if (typeof value === 'number' && Number.isFinite(value)) return value; if (typeof value === 'string' && value.trim() && Number.isFinite(Number(value))) return Number(value); return null; }
function normalizeAccounts(payload: unknown): DerivAccount[] {
  const root = (payload && typeof payload === 'object' ? payload : {}) as Record<string, unknown>;
  const data = root.data; const nested = data && typeof data === 'object' ? data as Record<string, unknown> : null;
  const candidates = Array.isArray(root.accounts) ? root.accounts : Array.isArray(nested?.accounts) ? nested.accounts : Array.isArray(data) ? data : [];
  return candidates.map((entry, index) => { const raw = (entry && typeof entry === 'object' ? entry : {}) as Record<string, unknown>; const balanceObject = raw.balance && typeof raw.balance === 'object' ? raw.balance as Record<string, unknown> : null; const accountType = String(raw.account_type ?? raw.accountType ?? raw.type ?? 'Options'); const id = String(raw.account_id ?? raw.accountId ?? raw.loginid ?? raw.id ?? `options-${index + 1}`); const label = String(raw.display_name ?? raw.account_name ?? raw.loginid ?? raw.account_id ?? raw.id ?? `Options account ${index + 1}`); const currency = String(raw.currency ?? balanceObject?.currency ?? 'USD'); const balance = numericValue(balanceObject?.amount ?? balanceObject?.value ?? raw.balance ?? raw.amount); const isDemo = /demo|virtual/i.test(`${accountType} ${id} ${String(raw.status ?? '')}`); return { id, label, accountType, currency, balance, isDemo }; });
}
export async function fetchDerivAccounts(accessToken: string) { const response = await fetch('/api/deriv/accounts', { headers: { Authorization: `Bearer ${accessToken}` }, cache: 'no-store' }); const payload = await response.json().catch(() => ({})); if (!response.ok) { const root = (payload && typeof payload === 'object' ? payload : {}) as Record<string, unknown>; const errors = Array.isArray(root.errors) ? root.errors as Array<Record<string, unknown>> : []; throw new Error(String(errors[0]?.message ?? root.error ?? `Deriv account sync failed (${response.status}).`)); } return normalizeAccounts(payload); }
